-- AUTO-GENERATED by scripts/generate-sqlite-triggers.ts — DO NOT EDIT BY HAND.
-- Regenerate: npm run generate:triggers
-- Covers exactly the 25 sensitive tables listed in AUDITED_TABLES.
-- users.passwordHash is explicitly excluded from every audit payload.


-- users ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_users_insert;
CREATE TRIGGER trg_audit_users_insert
AFTER INSERT ON users
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'users', NEW.id, NULL, json_object('id', NEW.id, 'username', NEW.username, 'fullName', NEW.fullName, 'roleId', NEW.roleId, 'isActive', NEW.isActive, 'lastLoginAt', NEW.lastLoginAt, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_users_update;
CREATE TRIGGER trg_audit_users_update
AFTER UPDATE ON users
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'users', NEW.id, json_object('id', OLD.id, 'username', OLD.username, 'fullName', OLD.fullName, 'roleId', OLD.roleId, 'isActive', OLD.isActive, 'lastLoginAt', OLD.lastLoginAt, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'username', NEW.username, 'fullName', NEW.fullName, 'roleId', NEW.roleId, 'isActive', NEW.isActive, 'lastLoginAt', NEW.lastLoginAt, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_users_delete;
CREATE TRIGGER trg_audit_users_delete
AFTER DELETE ON users
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'users', OLD.id, json_object('id', OLD.id, 'username', OLD.username, 'fullName', OLD.fullName, 'roleId', OLD.roleId, 'isActive', OLD.isActive, 'lastLoginAt', OLD.lastLoginAt, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- roles ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_roles_insert;
CREATE TRIGGER trg_audit_roles_insert
AFTER INSERT ON roles
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'roles', NEW.id, NULL, json_object('id', NEW.id, 'name', NEW.name, 'description', NEW.description, 'isSystem', NEW.isSystem, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_roles_update;
CREATE TRIGGER trg_audit_roles_update
AFTER UPDATE ON roles
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'roles', NEW.id, json_object('id', OLD.id, 'name', OLD.name, 'description', OLD.description, 'isSystem', OLD.isSystem, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'name', NEW.name, 'description', NEW.description, 'isSystem', NEW.isSystem, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_roles_delete;
CREATE TRIGGER trg_audit_roles_delete
AFTER DELETE ON roles
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'roles', OLD.id, json_object('id', OLD.id, 'name', OLD.name, 'description', OLD.description, 'isSystem', OLD.isSystem, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- role_permissions ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_role_permissions_insert;
CREATE TRIGGER trg_audit_role_permissions_insert
AFTER INSERT ON role_permissions
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'role_permissions', NEW.id, NULL, json_object('id', NEW.id, 'roleId', NEW.roleId, 'permissionId', NEW.permissionId), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_role_permissions_update;
CREATE TRIGGER trg_audit_role_permissions_update
AFTER UPDATE ON role_permissions
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'role_permissions', NEW.id, json_object('id', OLD.id, 'roleId', OLD.roleId, 'permissionId', OLD.permissionId), json_object('id', NEW.id, 'roleId', NEW.roleId, 'permissionId', NEW.permissionId), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_role_permissions_delete;
CREATE TRIGGER trg_audit_role_permissions_delete
AFTER DELETE ON role_permissions
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'role_permissions', OLD.id, json_object('id', OLD.id, 'roleId', OLD.roleId, 'permissionId', OLD.permissionId), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- families ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_families_insert;
CREATE TRIGGER trg_audit_families_insert
AFTER INSERT ON families
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'families', NEW.id, NULL, json_object('id', NEW.id, 'familyCode', NEW.familyCode, 'headOfFamilyName', NEW.headOfFamilyName, 'headNationalId', NEW.headNationalId, 'address', NEW.address, 'city', NEW.city, 'phone', NEW.phone, 'altPhone', NEW.altPhone, 'housingType', NEW.housingType, 'monthlyIncomeFils', NEW.monthlyIncomeFils, 'economicLevel', NEW.economicLevel, 'notes', NEW.notes, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_families_update;
CREATE TRIGGER trg_audit_families_update
AFTER UPDATE ON families
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'families', NEW.id, json_object('id', OLD.id, 'familyCode', OLD.familyCode, 'headOfFamilyName', OLD.headOfFamilyName, 'headNationalId', OLD.headNationalId, 'address', OLD.address, 'city', OLD.city, 'phone', OLD.phone, 'altPhone', OLD.altPhone, 'housingType', OLD.housingType, 'monthlyIncomeFils', OLD.monthlyIncomeFils, 'economicLevel', OLD.economicLevel, 'notes', OLD.notes, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'familyCode', NEW.familyCode, 'headOfFamilyName', NEW.headOfFamilyName, 'headNationalId', NEW.headNationalId, 'address', NEW.address, 'city', NEW.city, 'phone', NEW.phone, 'altPhone', NEW.altPhone, 'housingType', NEW.housingType, 'monthlyIncomeFils', NEW.monthlyIncomeFils, 'economicLevel', NEW.economicLevel, 'notes', NEW.notes, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_families_delete;
CREATE TRIGGER trg_audit_families_delete
AFTER DELETE ON families
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'families', OLD.id, json_object('id', OLD.id, 'familyCode', OLD.familyCode, 'headOfFamilyName', OLD.headOfFamilyName, 'headNationalId', OLD.headNationalId, 'address', OLD.address, 'city', OLD.city, 'phone', OLD.phone, 'altPhone', OLD.altPhone, 'housingType', OLD.housingType, 'monthlyIncomeFils', OLD.monthlyIncomeFils, 'economicLevel', OLD.economicLevel, 'notes', OLD.notes, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- family_members ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_family_members_insert;
CREATE TRIGGER trg_audit_family_members_insert
AFTER INSERT ON family_members
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'family_members', NEW.id, NULL, json_object('id', NEW.id, 'familyId', NEW.familyId, 'fullName', NEW.fullName, 'nationalId', NEW.nationalId, 'relationship', NEW.relationship, 'gender', NEW.gender, 'birthDate', NEW.birthDate, 'isDisabled', NEW.isDisabled, 'isStudent', NEW.isStudent, 'healthStatus', NEW.healthStatus, 'occupation', NEW.occupation, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_family_members_update;
CREATE TRIGGER trg_audit_family_members_update
AFTER UPDATE ON family_members
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'family_members', NEW.id, json_object('id', OLD.id, 'familyId', OLD.familyId, 'fullName', OLD.fullName, 'nationalId', OLD.nationalId, 'relationship', OLD.relationship, 'gender', OLD.gender, 'birthDate', OLD.birthDate, 'isDisabled', OLD.isDisabled, 'isStudent', OLD.isStudent, 'healthStatus', OLD.healthStatus, 'occupation', OLD.occupation, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'familyId', NEW.familyId, 'fullName', NEW.fullName, 'nationalId', NEW.nationalId, 'relationship', NEW.relationship, 'gender', NEW.gender, 'birthDate', NEW.birthDate, 'isDisabled', NEW.isDisabled, 'isStudent', NEW.isStudent, 'healthStatus', NEW.healthStatus, 'occupation', NEW.occupation, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_family_members_delete;
CREATE TRIGGER trg_audit_family_members_delete
AFTER DELETE ON family_members
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'family_members', OLD.id, json_object('id', OLD.id, 'familyId', OLD.familyId, 'fullName', OLD.fullName, 'nationalId', OLD.nationalId, 'relationship', OLD.relationship, 'gender', OLD.gender, 'birthDate', OLD.birthDate, 'isDisabled', OLD.isDisabled, 'isStudent', OLD.isStudent, 'healthStatus', OLD.healthStatus, 'occupation', OLD.occupation, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- beneficiaries ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_beneficiaries_insert;
CREATE TRIGGER trg_audit_beneficiaries_insert
AFTER INSERT ON beneficiaries
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'beneficiaries', NEW.id, NULL, json_object('id', NEW.id, 'familyId', NEW.familyId, 'fullName', NEW.fullName, 'nationalId', NEW.nationalId, 'phone', NEW.phone, 'birthDate', NEW.birthDate, 'gender', NEW.gender, 'category', NEW.category, 'status', NEW.status, 'notes', NEW.notes, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_beneficiaries_update;
CREATE TRIGGER trg_audit_beneficiaries_update
AFTER UPDATE ON beneficiaries
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'beneficiaries', NEW.id, json_object('id', OLD.id, 'familyId', OLD.familyId, 'fullName', OLD.fullName, 'nationalId', OLD.nationalId, 'phone', OLD.phone, 'birthDate', OLD.birthDate, 'gender', OLD.gender, 'category', OLD.category, 'status', OLD.status, 'notes', OLD.notes, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'familyId', NEW.familyId, 'fullName', NEW.fullName, 'nationalId', NEW.nationalId, 'phone', NEW.phone, 'birthDate', NEW.birthDate, 'gender', NEW.gender, 'category', NEW.category, 'status', NEW.status, 'notes', NEW.notes, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_beneficiaries_delete;
CREATE TRIGGER trg_audit_beneficiaries_delete
AFTER DELETE ON beneficiaries
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'beneficiaries', OLD.id, json_object('id', OLD.id, 'familyId', OLD.familyId, 'fullName', OLD.fullName, 'nationalId', OLD.nationalId, 'phone', OLD.phone, 'birthDate', OLD.birthDate, 'gender', OLD.gender, 'category', OLD.category, 'status', OLD.status, 'notes', OLD.notes, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- social_assessments ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_social_assessments_insert;
CREATE TRIGGER trg_audit_social_assessments_insert
AFTER INSERT ON social_assessments
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'social_assessments', NEW.id, NULL, json_object('id', NEW.id, 'familyId', NEW.familyId, 'beneficiaryId', NEW.beneficiaryId, 'researcherId', NEW.researcherId, 'assessmentDate', NEW.assessmentDate, 'economicLevel', NEW.economicLevel, 'housingCondition', NEW.housingCondition, 'healthCondition', NEW.healthCondition, 'educationLevel', NEW.educationLevel, 'recommendation', NEW.recommendation, 'score', NEW.score, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_social_assessments_update;
CREATE TRIGGER trg_audit_social_assessments_update
AFTER UPDATE ON social_assessments
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'social_assessments', NEW.id, json_object('id', OLD.id, 'familyId', OLD.familyId, 'beneficiaryId', OLD.beneficiaryId, 'researcherId', OLD.researcherId, 'assessmentDate', OLD.assessmentDate, 'economicLevel', OLD.economicLevel, 'housingCondition', OLD.housingCondition, 'healthCondition', OLD.healthCondition, 'educationLevel', OLD.educationLevel, 'recommendation', OLD.recommendation, 'score', OLD.score, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'familyId', NEW.familyId, 'beneficiaryId', NEW.beneficiaryId, 'researcherId', NEW.researcherId, 'assessmentDate', NEW.assessmentDate, 'economicLevel', NEW.economicLevel, 'housingCondition', NEW.housingCondition, 'healthCondition', NEW.healthCondition, 'educationLevel', NEW.educationLevel, 'recommendation', NEW.recommendation, 'score', NEW.score, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_social_assessments_delete;
CREATE TRIGGER trg_audit_social_assessments_delete
AFTER DELETE ON social_assessments
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'social_assessments', OLD.id, json_object('id', OLD.id, 'familyId', OLD.familyId, 'beneficiaryId', OLD.beneficiaryId, 'researcherId', OLD.researcherId, 'assessmentDate', OLD.assessmentDate, 'economicLevel', OLD.economicLevel, 'housingCondition', OLD.housingCondition, 'healthCondition', OLD.healthCondition, 'educationLevel', OLD.educationLevel, 'recommendation', OLD.recommendation, 'score', OLD.score, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- field_visits ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_field_visits_insert;
CREATE TRIGGER trg_audit_field_visits_insert
AFTER INSERT ON field_visits
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'field_visits', NEW.id, NULL, json_object('id', NEW.id, 'familyId', NEW.familyId, 'userId', NEW.userId, 'visitDate', NEW.visitDate, 'purpose', NEW.purpose, 'findings', NEW.findings, 'status', NEW.status, 'nextVisitAt', NEW.nextVisitAt, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_field_visits_update;
CREATE TRIGGER trg_audit_field_visits_update
AFTER UPDATE ON field_visits
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'field_visits', NEW.id, json_object('id', OLD.id, 'familyId', OLD.familyId, 'userId', OLD.userId, 'visitDate', OLD.visitDate, 'purpose', OLD.purpose, 'findings', OLD.findings, 'status', OLD.status, 'nextVisitAt', OLD.nextVisitAt, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'familyId', NEW.familyId, 'userId', NEW.userId, 'visitDate', NEW.visitDate, 'purpose', NEW.purpose, 'findings', NEW.findings, 'status', NEW.status, 'nextVisitAt', NEW.nextVisitAt, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_field_visits_delete;
CREATE TRIGGER trg_audit_field_visits_delete
AFTER DELETE ON field_visits
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'field_visits', OLD.id, json_object('id', OLD.id, 'familyId', OLD.familyId, 'userId', OLD.userId, 'visitDate', OLD.visitDate, 'purpose', OLD.purpose, 'findings', OLD.findings, 'status', OLD.status, 'nextVisitAt', OLD.nextVisitAt, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- assistance_types ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_assistance_types_insert;
CREATE TRIGGER trg_audit_assistance_types_insert
AFTER INSERT ON assistance_types
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'assistance_types', NEW.id, NULL, json_object('id', NEW.id, 'name', NEW.name, 'category', NEW.category, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_assistance_types_update;
CREATE TRIGGER trg_audit_assistance_types_update
AFTER UPDATE ON assistance_types
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'assistance_types', NEW.id, json_object('id', OLD.id, 'name', OLD.name, 'category', OLD.category, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'name', NEW.name, 'category', NEW.category, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_assistance_types_delete;
CREATE TRIGGER trg_audit_assistance_types_delete
AFTER DELETE ON assistance_types
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'assistance_types', OLD.id, json_object('id', OLD.id, 'name', OLD.name, 'category', OLD.category, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- assistances ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_assistances_insert;
CREATE TRIGGER trg_audit_assistances_insert
AFTER INSERT ON assistances
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'assistances', NEW.id, NULL, json_object('id', NEW.id, 'beneficiaryId', NEW.beneficiaryId, 'familyId', NEW.familyId, 'assistanceTypeId', NEW.assistanceTypeId, 'campaignId', NEW.campaignId, 'amountFils', NEW.amountFils, 'inventoryItemId', NEW.inventoryItemId, 'quantity', NEW.quantity, 'status', NEW.status, 'approvedById', NEW.approvedById, 'disbursedAt', NEW.disbursedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_assistances_update;
CREATE TRIGGER trg_audit_assistances_update
AFTER UPDATE ON assistances
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'assistances', NEW.id, json_object('id', OLD.id, 'beneficiaryId', OLD.beneficiaryId, 'familyId', OLD.familyId, 'assistanceTypeId', OLD.assistanceTypeId, 'campaignId', OLD.campaignId, 'amountFils', OLD.amountFils, 'inventoryItemId', OLD.inventoryItemId, 'quantity', OLD.quantity, 'status', OLD.status, 'approvedById', OLD.approvedById, 'disbursedAt', OLD.disbursedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'beneficiaryId', NEW.beneficiaryId, 'familyId', NEW.familyId, 'assistanceTypeId', NEW.assistanceTypeId, 'campaignId', NEW.campaignId, 'amountFils', NEW.amountFils, 'inventoryItemId', NEW.inventoryItemId, 'quantity', NEW.quantity, 'status', NEW.status, 'approvedById', NEW.approvedById, 'disbursedAt', NEW.disbursedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_assistances_delete;
CREATE TRIGGER trg_audit_assistances_delete
AFTER DELETE ON assistances
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'assistances', OLD.id, json_object('id', OLD.id, 'beneficiaryId', OLD.beneficiaryId, 'familyId', OLD.familyId, 'assistanceTypeId', OLD.assistanceTypeId, 'campaignId', OLD.campaignId, 'amountFils', OLD.amountFils, 'inventoryItemId', OLD.inventoryItemId, 'quantity', OLD.quantity, 'status', OLD.status, 'approvedById', OLD.approvedById, 'disbursedAt', OLD.disbursedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- campaigns ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_campaigns_insert;
CREATE TRIGGER trg_audit_campaigns_insert
AFTER INSERT ON campaigns
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'campaigns', NEW.id, NULL, json_object('id', NEW.id, 'name', NEW.name, 'description', NEW.description, 'startDate', NEW.startDate, 'endDate', NEW.endDate, 'targetAmountFils', NEW.targetAmountFils, 'status', NEW.status, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_campaigns_update;
CREATE TRIGGER trg_audit_campaigns_update
AFTER UPDATE ON campaigns
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'campaigns', NEW.id, json_object('id', OLD.id, 'name', OLD.name, 'description', OLD.description, 'startDate', OLD.startDate, 'endDate', OLD.endDate, 'targetAmountFils', OLD.targetAmountFils, 'status', OLD.status, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'name', NEW.name, 'description', NEW.description, 'startDate', NEW.startDate, 'endDate', NEW.endDate, 'targetAmountFils', NEW.targetAmountFils, 'status', NEW.status, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_campaigns_delete;
CREATE TRIGGER trg_audit_campaigns_delete
AFTER DELETE ON campaigns
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'campaigns', OLD.id, json_object('id', OLD.id, 'name', OLD.name, 'description', OLD.description, 'startDate', OLD.startDate, 'endDate', OLD.endDate, 'targetAmountFils', OLD.targetAmountFils, 'status', OLD.status, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- campaign_items ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_campaign_items_insert;
CREATE TRIGGER trg_audit_campaign_items_insert
AFTER INSERT ON campaign_items
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'campaign_items', NEW.id, NULL, json_object('id', NEW.id, 'campaignId', NEW.campaignId, 'beneficiaryId', NEW.beneficiaryId, 'plannedAmountFils', NEW.plannedAmountFils, 'status', NEW.status, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_campaign_items_update;
CREATE TRIGGER trg_audit_campaign_items_update
AFTER UPDATE ON campaign_items
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'campaign_items', NEW.id, json_object('id', OLD.id, 'campaignId', OLD.campaignId, 'beneficiaryId', OLD.beneficiaryId, 'plannedAmountFils', OLD.plannedAmountFils, 'status', OLD.status, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'campaignId', NEW.campaignId, 'beneficiaryId', NEW.beneficiaryId, 'plannedAmountFils', NEW.plannedAmountFils, 'status', NEW.status, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_campaign_items_delete;
CREATE TRIGGER trg_audit_campaign_items_delete
AFTER DELETE ON campaign_items
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'campaign_items', OLD.id, json_object('id', OLD.id, 'campaignId', OLD.campaignId, 'beneficiaryId', OLD.beneficiaryId, 'plannedAmountFils', OLD.plannedAmountFils, 'status', OLD.status, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- warehouses ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_warehouses_insert;
CREATE TRIGGER trg_audit_warehouses_insert
AFTER INSERT ON warehouses
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'warehouses', NEW.id, NULL, json_object('id', NEW.id, 'name', NEW.name, 'location', NEW.location, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_warehouses_update;
CREATE TRIGGER trg_audit_warehouses_update
AFTER UPDATE ON warehouses
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'warehouses', NEW.id, json_object('id', OLD.id, 'name', OLD.name, 'location', OLD.location, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'name', NEW.name, 'location', NEW.location, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_warehouses_delete;
CREATE TRIGGER trg_audit_warehouses_delete
AFTER DELETE ON warehouses
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'warehouses', OLD.id, json_object('id', OLD.id, 'name', OLD.name, 'location', OLD.location, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- inventory_items ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_inventory_items_insert;
CREATE TRIGGER trg_audit_inventory_items_insert
AFTER INSERT ON inventory_items
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'inventory_items', NEW.id, NULL, json_object('id', NEW.id, 'warehouseId', NEW.warehouseId, 'name', NEW.name, 'unit', NEW.unit, 'quantity', NEW.quantity, 'minQuantity', NEW.minQuantity, 'unitPriceFils', NEW.unitPriceFils, 'category', NEW.category, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_inventory_items_update;
CREATE TRIGGER trg_audit_inventory_items_update
AFTER UPDATE ON inventory_items
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'inventory_items', NEW.id, json_object('id', OLD.id, 'warehouseId', OLD.warehouseId, 'name', OLD.name, 'unit', OLD.unit, 'quantity', OLD.quantity, 'minQuantity', OLD.minQuantity, 'unitPriceFils', OLD.unitPriceFils, 'category', OLD.category, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'warehouseId', NEW.warehouseId, 'name', NEW.name, 'unit', NEW.unit, 'quantity', NEW.quantity, 'minQuantity', NEW.minQuantity, 'unitPriceFils', NEW.unitPriceFils, 'category', NEW.category, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_inventory_items_delete;
CREATE TRIGGER trg_audit_inventory_items_delete
AFTER DELETE ON inventory_items
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'inventory_items', OLD.id, json_object('id', OLD.id, 'warehouseId', OLD.warehouseId, 'name', OLD.name, 'unit', OLD.unit, 'quantity', OLD.quantity, 'minQuantity', OLD.minQuantity, 'unitPriceFils', OLD.unitPriceFils, 'category', OLD.category, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- stock_in ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_stock_in_insert;
CREATE TRIGGER trg_audit_stock_in_insert
AFTER INSERT ON stock_in
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'stock_in', NEW.id, NULL, json_object('id', NEW.id, 'inventoryItemId', NEW.inventoryItemId, 'supplierId', NEW.supplierId, 'quantity', NEW.quantity, 'unitPriceFils', NEW.unitPriceFils, 'totalFils', NEW.totalFils, 'referenceNo', NEW.referenceNo, 'receivedAt', NEW.receivedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_stock_in_update;
CREATE TRIGGER trg_audit_stock_in_update
AFTER UPDATE ON stock_in
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'stock_in', NEW.id, json_object('id', OLD.id, 'inventoryItemId', OLD.inventoryItemId, 'supplierId', OLD.supplierId, 'quantity', OLD.quantity, 'unitPriceFils', OLD.unitPriceFils, 'totalFils', OLD.totalFils, 'referenceNo', OLD.referenceNo, 'receivedAt', OLD.receivedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'inventoryItemId', NEW.inventoryItemId, 'supplierId', NEW.supplierId, 'quantity', NEW.quantity, 'unitPriceFils', NEW.unitPriceFils, 'totalFils', NEW.totalFils, 'referenceNo', NEW.referenceNo, 'receivedAt', NEW.receivedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_stock_in_delete;
CREATE TRIGGER trg_audit_stock_in_delete
AFTER DELETE ON stock_in
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'stock_in', OLD.id, json_object('id', OLD.id, 'inventoryItemId', OLD.inventoryItemId, 'supplierId', OLD.supplierId, 'quantity', OLD.quantity, 'unitPriceFils', OLD.unitPriceFils, 'totalFils', OLD.totalFils, 'referenceNo', OLD.referenceNo, 'receivedAt', OLD.receivedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- stock_out ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_stock_out_insert;
CREATE TRIGGER trg_audit_stock_out_insert
AFTER INSERT ON stock_out
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'stock_out', NEW.id, NULL, json_object('id', NEW.id, 'inventoryItemId', NEW.inventoryItemId, 'quantity', NEW.quantity, 'reason', NEW.reason, 'referenceId', NEW.referenceId, 'issuedAt', NEW.issuedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_stock_out_update;
CREATE TRIGGER trg_audit_stock_out_update
AFTER UPDATE ON stock_out
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'stock_out', NEW.id, json_object('id', OLD.id, 'inventoryItemId', OLD.inventoryItemId, 'quantity', OLD.quantity, 'reason', OLD.reason, 'referenceId', OLD.referenceId, 'issuedAt', OLD.issuedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'inventoryItemId', NEW.inventoryItemId, 'quantity', NEW.quantity, 'reason', NEW.reason, 'referenceId', NEW.referenceId, 'issuedAt', NEW.issuedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_stock_out_delete;
CREATE TRIGGER trg_audit_stock_out_delete
AFTER DELETE ON stock_out
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'stock_out', OLD.id, json_object('id', OLD.id, 'inventoryItemId', OLD.inventoryItemId, 'quantity', OLD.quantity, 'reason', OLD.reason, 'referenceId', OLD.referenceId, 'issuedAt', OLD.issuedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- suppliers ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_suppliers_insert;
CREATE TRIGGER trg_audit_suppliers_insert
AFTER INSERT ON suppliers
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'suppliers', NEW.id, NULL, json_object('id', NEW.id, 'name', NEW.name, 'phone', NEW.phone, 'address', NEW.address, 'notes', NEW.notes, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_suppliers_update;
CREATE TRIGGER trg_audit_suppliers_update
AFTER UPDATE ON suppliers
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'suppliers', NEW.id, json_object('id', OLD.id, 'name', OLD.name, 'phone', OLD.phone, 'address', OLD.address, 'notes', OLD.notes, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'name', NEW.name, 'phone', NEW.phone, 'address', NEW.address, 'notes', NEW.notes, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_suppliers_delete;
CREATE TRIGGER trg_audit_suppliers_delete
AFTER DELETE ON suppliers
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'suppliers', OLD.id, json_object('id', OLD.id, 'name', OLD.name, 'phone', OLD.phone, 'address', OLD.address, 'notes', OLD.notes, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- donors ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_donors_insert;
CREATE TRIGGER trg_audit_donors_insert
AFTER INSERT ON donors
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'donors', NEW.id, NULL, json_object('id', NEW.id, 'name', NEW.name, 'phone', NEW.phone, 'email', NEW.email, 'address', NEW.address, 'donorType', NEW.donorType, 'notes', NEW.notes, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_donors_update;
CREATE TRIGGER trg_audit_donors_update
AFTER UPDATE ON donors
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'donors', NEW.id, json_object('id', OLD.id, 'name', OLD.name, 'phone', OLD.phone, 'email', OLD.email, 'address', OLD.address, 'donorType', OLD.donorType, 'notes', OLD.notes, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'name', NEW.name, 'phone', NEW.phone, 'email', NEW.email, 'address', NEW.address, 'donorType', NEW.donorType, 'notes', NEW.notes, 'isActive', NEW.isActive, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_donors_delete;
CREATE TRIGGER trg_audit_donors_delete
AFTER DELETE ON donors
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'donors', OLD.id, json_object('id', OLD.id, 'name', OLD.name, 'phone', OLD.phone, 'email', OLD.email, 'address', OLD.address, 'donorType', OLD.donorType, 'notes', OLD.notes, 'isActive', OLD.isActive, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- donations ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_donations_insert;
CREATE TRIGGER trg_audit_donations_insert
AFTER INSERT ON donations
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'donations', NEW.id, NULL, json_object('id', NEW.id, 'donorId', NEW.donorId, 'amountFils', NEW.amountFils, 'donationType', NEW.donationType, 'method', NEW.method, 'donatedAt', NEW.donatedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_donations_update;
CREATE TRIGGER trg_audit_donations_update
AFTER UPDATE ON donations
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'donations', NEW.id, json_object('id', OLD.id, 'donorId', OLD.donorId, 'amountFils', OLD.amountFils, 'donationType', OLD.donationType, 'method', OLD.method, 'donatedAt', OLD.donatedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'donorId', NEW.donorId, 'amountFils', NEW.amountFils, 'donationType', NEW.donationType, 'method', NEW.method, 'donatedAt', NEW.donatedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_donations_delete;
CREATE TRIGGER trg_audit_donations_delete
AFTER DELETE ON donations
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'donations', OLD.id, json_object('id', OLD.id, 'donorId', OLD.donorId, 'amountFils', OLD.amountFils, 'donationType', OLD.donationType, 'method', OLD.method, 'donatedAt', OLD.donatedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- receipts ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_receipts_insert;
CREATE TRIGGER trg_audit_receipts_insert
AFTER INSERT ON receipts
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'receipts', NEW.id, NULL, json_object('id', NEW.id, 'donationId', NEW.donationId, 'receiptNo', NEW.receiptNo, 'amountFils', NEW.amountFils, 'issuedAt', NEW.issuedAt, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_receipts_update;
CREATE TRIGGER trg_audit_receipts_update
AFTER UPDATE ON receipts
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'receipts', NEW.id, json_object('id', OLD.id, 'donationId', OLD.donationId, 'receiptNo', OLD.receiptNo, 'amountFils', OLD.amountFils, 'issuedAt', OLD.issuedAt, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'donationId', NEW.donationId, 'receiptNo', NEW.receiptNo, 'amountFils', NEW.amountFils, 'issuedAt', NEW.issuedAt, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_receipts_delete;
CREATE TRIGGER trg_audit_receipts_delete
AFTER DELETE ON receipts
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'receipts', OLD.id, json_object('id', OLD.id, 'donationId', OLD.donationId, 'receiptNo', OLD.receiptNo, 'amountFils', OLD.amountFils, 'issuedAt', OLD.issuedAt, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- transactions ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_transactions_insert;
CREATE TRIGGER trg_audit_transactions_insert
AFTER INSERT ON transactions
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'transactions', NEW.id, NULL, json_object('id', NEW.id, 'type', NEW.type, 'amountFils', NEW.amountFils, 'categoryId', NEW.categoryId, 'description', NEW.description, 'referenceType', NEW.referenceType, 'referenceId', NEW.referenceId, 'transactionAt', NEW.transactionAt, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_transactions_update;
CREATE TRIGGER trg_audit_transactions_update
AFTER UPDATE ON transactions
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'transactions', NEW.id, json_object('id', OLD.id, 'type', OLD.type, 'amountFils', OLD.amountFils, 'categoryId', OLD.categoryId, 'description', OLD.description, 'referenceType', OLD.referenceType, 'referenceId', OLD.referenceId, 'transactionAt', OLD.transactionAt, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'type', NEW.type, 'amountFils', NEW.amountFils, 'categoryId', NEW.categoryId, 'description', NEW.description, 'referenceType', NEW.referenceType, 'referenceId', NEW.referenceId, 'transactionAt', NEW.transactionAt, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_transactions_delete;
CREATE TRIGGER trg_audit_transactions_delete
AFTER DELETE ON transactions
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'transactions', OLD.id, json_object('id', OLD.id, 'type', OLD.type, 'amountFils', OLD.amountFils, 'categoryId', OLD.categoryId, 'description', OLD.description, 'referenceType', OLD.referenceType, 'referenceId', OLD.referenceId, 'transactionAt', OLD.transactionAt, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- attachments ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_attachments_insert;
CREATE TRIGGER trg_audit_attachments_insert
AFTER INSERT ON attachments
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'attachments', NEW.id, NULL, json_object('id', NEW.id, 'fileName', NEW.fileName, 'storedName', NEW.storedName, 'entityType', NEW.entityType, 'entityId', NEW.entityId, 'mimeType', NEW.mimeType, 'sizeBytes', NEW.sizeBytes, 'uploadedById', NEW.uploadedById, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_attachments_update;
CREATE TRIGGER trg_audit_attachments_update
AFTER UPDATE ON attachments
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'attachments', NEW.id, json_object('id', OLD.id, 'fileName', OLD.fileName, 'storedName', OLD.storedName, 'entityType', OLD.entityType, 'entityId', OLD.entityId, 'mimeType', OLD.mimeType, 'sizeBytes', OLD.sizeBytes, 'uploadedById', OLD.uploadedById, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'fileName', NEW.fileName, 'storedName', NEW.storedName, 'entityType', NEW.entityType, 'entityId', NEW.entityId, 'mimeType', NEW.mimeType, 'sizeBytes', NEW.sizeBytes, 'uploadedById', NEW.uploadedById, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_attachments_delete;
CREATE TRIGGER trg_audit_attachments_delete
AFTER DELETE ON attachments
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'attachments', OLD.id, json_object('id', OLD.id, 'fileName', OLD.fileName, 'storedName', OLD.storedName, 'entityType', OLD.entityType, 'entityId', OLD.entityId, 'mimeType', OLD.mimeType, 'sizeBytes', OLD.sizeBytes, 'uploadedById', OLD.uploadedById, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- notifications ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_notifications_insert;
CREATE TRIGGER trg_audit_notifications_insert
AFTER INSERT ON notifications
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'notifications', NEW.id, NULL, json_object('id', NEW.id, 'userId', NEW.userId, 'title', NEW.title, 'message', NEW.message, 'isRead', NEW.isRead, 'level', NEW.level, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_notifications_update;
CREATE TRIGGER trg_audit_notifications_update
AFTER UPDATE ON notifications
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'notifications', NEW.id, json_object('id', OLD.id, 'userId', OLD.userId, 'title', OLD.title, 'message', OLD.message, 'isRead', OLD.isRead, 'level', OLD.level, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'userId', NEW.userId, 'title', NEW.title, 'message', NEW.message, 'isRead', NEW.isRead, 'level', NEW.level, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_notifications_delete;
CREATE TRIGGER trg_audit_notifications_delete
AFTER DELETE ON notifications
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'notifications', OLD.id, json_object('id', OLD.id, 'userId', OLD.userId, 'title', OLD.title, 'message', OLD.message, 'isRead', OLD.isRead, 'level', OLD.level, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- approvals ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_approvals_insert;
CREATE TRIGGER trg_audit_approvals_insert
AFTER INSERT ON approvals
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'approvals', NEW.id, NULL, json_object('id', NEW.id, 'entityType', NEW.entityType, 'entityId', NEW.entityId, 'status', NEW.status, 'requestedById', NEW.requestedById, 'approvedById', NEW.approvedById, 'decidedAt', NEW.decidedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_approvals_update;
CREATE TRIGGER trg_audit_approvals_update
AFTER UPDATE ON approvals
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'approvals', NEW.id, json_object('id', OLD.id, 'entityType', OLD.entityType, 'entityId', OLD.entityId, 'status', OLD.status, 'requestedById', OLD.requestedById, 'approvedById', OLD.approvedById, 'decidedAt', OLD.decidedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), json_object('id', NEW.id, 'entityType', NEW.entityType, 'entityId', NEW.entityId, 'status', NEW.status, 'requestedById', NEW.requestedById, 'approvedById', NEW.approvedById, 'decidedAt', NEW.decidedAt, 'notes', NEW.notes, 'createdAt', NEW.createdAt, 'updatedAt', NEW.updatedAt), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_approvals_delete;
CREATE TRIGGER trg_audit_approvals_delete
AFTER DELETE ON approvals
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'approvals', OLD.id, json_object('id', OLD.id, 'entityType', OLD.entityType, 'entityId', OLD.entityId, 'status', OLD.status, 'requestedById', OLD.requestedById, 'approvedById', OLD.approvedById, 'decidedAt', OLD.decidedAt, 'notes', OLD.notes, 'createdAt', OLD.createdAt, 'updatedAt', OLD.updatedAt), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;


-- settings ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_settings_insert;
CREATE TRIGGER trg_audit_settings_insert
AFTER INSERT ON settings
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', 'settings', NEW.id, NULL, json_object('id', NEW.id, 'key', NEW.key, 'value', NEW.value), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_settings_update;
CREATE TRIGGER trg_audit_settings_update
AFTER UPDATE ON settings
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', 'settings', NEW.id, json_object('id', OLD.id, 'key', OLD.key, 'value', OLD.value), json_object('id', NEW.id, 'key', NEW.key, 'value', NEW.value), strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;

DROP TRIGGER IF EXISTS trg_audit_settings_delete;
CREATE TRIGGER trg_audit_settings_delete
AFTER DELETE ON settings
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', 'settings', OLD.id, json_object('id', OLD.id, 'key', OLD.key, 'value', OLD.value), NULL, strftime('%Y-%m-%dT%H:%M:%fZ','now')
  );
END;
