/**
 * AUTO-GENERATES prisma/sqlite-sql/audit-triggers.sql from the Prisma DMMF.
 * Do not hand-edit the generated file — edit this generator instead, then
 * run `npm run generate:triggers`.
 *
 * Covers exactly the sensitive tables listed in AUDITED_TABLES (25 total).
 * `password_hash` (users.passwordHash) is explicitly excluded from every
 * audit payload so credential hashes never land in audit_logs.
 */
// The client is generated to ../generated/prisma (see the `output` note in
// schema.prisma), so '@prisma/client' here resolves to the unpopulated stub
// package and carries no DMMF.
import { Prisma } from '../generated/prisma';
import fs from 'node:fs';
import path from 'node:path';

const AUDITED_TABLES = [
  'users', 'roles', 'role_permissions', 'regions', 'families', 'family_members', 'beneficiaries',
  'social_assessments', 'field_visits', 'assistance_types', 'assistances', 'campaigns',
  'campaign_items', 'warehouses', 'inventory_items', 'stock_in', 'stock_out', 'suppliers',
  'donors', 'donations', 'receipts', 'transactions', 'attachments', 'notifications',
  'approvals', 'settings', 'import_batches',
] as const;

const EXCLUDED_COLUMNS: Record<string, string[]> = {
  users: ['passwordHash'],
};

// ISO-8601 with milliseconds ('...Z'), matching the format Prisma writes
// for DateTime columns on SQLite, so audit_logs.createdAt reads back cleanly.
const NOW_EXPR = `strftime('%Y-%m-%dT%H:%M:%fZ','now')`;

type DmmfModel = (typeof Prisma.dmmf.datamodel.models)[number];

function scalarColumns(model: DmmfModel, excluded: string[]): string[] {
  return model.fields
    .filter((f) => f.kind === 'scalar')
    .map((f) => f.name)
    .filter((name) => !excluded.includes(name));
}

function jsonObjectExpr(alias: 'NEW' | 'OLD', columns: string[]): string {
  return `json_object(${columns.map((c) => `'${c}', ${alias}.${c}`).join(', ')})`;
}

function buildTriggers(table: string, model: DmmfModel): string {
  const excluded = EXCLUDED_COLUMNS[table] ?? [];
  const columns = scalarColumns(model, excluded);
  const newJson = jsonObjectExpr('NEW', columns);
  const oldJson = jsonObjectExpr('OLD', columns);

  return `
-- ${table} ------------------------------------------------------------------
DROP TRIGGER IF EXISTS trg_audit_${table}_insert;
CREATE TRIGGER trg_audit_${table}_insert
AFTER INSERT ON ${table}
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'INSERT', '${table}', NEW.id, NULL, ${newJson}, ${NOW_EXPR}
  );
END;

DROP TRIGGER IF EXISTS trg_audit_${table}_update;
CREATE TRIGGER trg_audit_${table}_update
AFTER UPDATE ON ${table}
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'UPDATE', '${table}', NEW.id, ${oldJson}, ${newJson}, ${NOW_EXPR}
  );
END;

DROP TRIGGER IF EXISTS trg_audit_${table}_delete;
CREATE TRIGGER trg_audit_${table}_delete
AFTER DELETE ON ${table}
FOR EACH ROW
BEGIN
  INSERT INTO audit_logs (id, userId, username, action, tableName, recordId, oldValues, newValues, createdAt)
  VALUES (
    lower(hex(randomblob(16))),
    (SELECT value FROM _audit_context WHERE key = 'current_user_id'),
    (SELECT value FROM _audit_context WHERE key = 'current_username'),
    'DELETE', '${table}', OLD.id, ${oldJson}, NULL, ${NOW_EXPR}
  );
END;
`;
}

function main() {
  const models = Prisma.dmmf.datamodel.models;
  const header = `-- AUTO-GENERATED by scripts/generate-sqlite-triggers.ts — DO NOT EDIT BY HAND.\n-- Regenerate: npm run generate:triggers\n-- Covers exactly the ${AUDITED_TABLES.length} sensitive tables listed in AUDITED_TABLES.\n-- users.passwordHash is explicitly excluded from every audit payload.\n`;
  const parts: string[] = [header];

  for (const table of AUDITED_TABLES) {
    const model = models.find((m) => (m.dbName ?? m.name) === table);
    if (!model) {
      throw new Error(`Model for table "${table}" not found in Prisma DMMF`);
    }
    parts.push(buildTriggers(table, model));
  }

  const outPath = path.join(__dirname, '..', 'prisma', 'sqlite-sql', 'audit-triggers.sql');
  fs.writeFileSync(outPath, parts.join('\n'), 'utf-8');
  console.log(`Generated audit triggers for ${AUDITED_TABLES.length} tables -> ${outPath}`);
}

main();
